apiVersion: v1
kind: Service
metadata:
  name: b2web
  namespace: budget2
  labels:
    app: b2web
    ver: prod
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: b2web
    ver: prod
