apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2web
  namespace: budget2
  labels: 
    app: b2web
    ver: prod
spec:
  replicas: 4
  selector:
    matchLabels:  #Deploy in a POD that has labels app: color and color: blue
      app: b2web
      ver: prod
  template: #For the creation of the pod      
    metadata:
      labels:
        app: b2web
        ver: prod
    spec:
      containers:
        - name: b2web
          image: k1.hb.noclab.com.au:31320/b2web:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          env:
            - name: B2_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
          envFrom:
            - configMapRef:
                name: b2web-prod-cm01
