apiVersion: v1
kind: ConfigMap
metadata:
  name: b2web-prod-cm01
  namespace: budget2
data:
  B2_PAYDAY: "15"
  B2_RENTDAY: "10"
  B2_RENTAMOUNT: "3000"
  B2_INITIALVALUES: "1:10000"
  B2_SENDERADDRESS: fake@fake.domain
  B2_EMAILRECIPIENTS: r1@fake.domain r2@fake.domain
  B2_DBUSERNAME: postgres
  B2_DBPASSWORD: password123
    # B2_DBSERVER: db01.hb.noclab.com.au
  B2_DBSERVER: "192.168.1.210"
  B2_DBNAME: budget2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2web
  namespace: budget2
  labels: 
    app: b2web
    ver: prod
spec:
  replicas: 4
  selector:
    matchLabels:  #Deploy in a POD that has labels app: color and color: blue
      app: b2web
      ver: prod
  template: #For the creation of the pod      
    metadata:
      labels:
        app: b2web
        ver: prod
    spec:
      containers:
        - name: b2web
          image: docker-registry:5000/budget2-web:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: b2web-prod-cm01
---
apiVersion: v1
kind: Service
metadata:
  name: b2web
  namespace: budget2
  labels:
    app: b2web
    ver: prod
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: b2web
    ver: prod
